modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]

modId="${mod_id}"
logoFile="icon.png"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/x-j0nnay-x/SimpelAdds-Update/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simpel-add-mod"
issueTrackerURL="https://github.com/x-j0nnay-x/Simpel-Adds/issues"
modUrl="https://www.curseforge.com/minecraft/mc-mods/simpel-add-mod"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]

    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}" #
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

